.TH "BLAZE" "1" "February 2023" "blaze 0.1" ""
.hy
.SH NAME
.PP
blaze - UCI compatible chess engine
.SH SYNOPSIS
.PP
\f[B]blaze\f[R] [\f[I]OPTION\f[R]]
.SH DESCRIPTION
.PP
\f[B]blaze\f[R] is a free and open source chess engine written in C
.SH OPTIONS
.TP
\f[B]-h\f[R], \f[B]--help\f[R]
display this help and exit.
.TP
\f[B]-v\f[R], \f[B]--version\f[R]
output version information and exit.
.SH BUGS
.PP
please report bugs at <https://github.com/blocr/blaze/issues>
.SH COPYRIGHT
.PP
blaze is a free software licensed under the MIT license, feel free to
change it or redistribute it.
